// src/services/brochure.js
import PDFDocument from "pdfkit";

/**
 * Draw a key-value line
 */
function kv(doc, key, val) {
  if (!val && val !== 0) return;
  doc.font("Helvetica-Bold").text(`${key}: `, { continued: true });
  doc.font("Helvetica").text(String(val));
}

/**
 * mm helper to place content with margins
 */
function startPage(doc) {
  doc.addPage({ margin: 36 }); // 0.5 inch
}

/**
 * Build and stream a PDF brochure to the response.
 * Assumes `prop` is a Property mongoose doc (or plain object).
 */
export async function streamBrochurePDF(prop, res, opts = {}) {
  const doc = new PDFDocument({ size: "A4", margin: 36 });
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `inline; filename="property-${prop._id}.pdf"`);

  doc.pipe(res);

  // Header
  doc.font("Helvetica-Bold").fontSize(18).text("Chandrapur Real Estate — Property Brochure");
  doc.moveDown(0.5);
  doc.fontSize(12).font("Helvetica").text(new Date().toLocaleString());
  doc.moveDown();

  // Title block
  const title = [
    prop?.parcel?.survey_gat_no ? `Gat ${prop.parcel.survey_gat_no}` : null,
    prop?.parcel?.ulpin ? `ULPIN ${prop.parcel.ulpin}` : null,
  ].filter(Boolean).join(" • ");

  doc.fontSize(16).font("Helvetica-Bold").text(title || "Property");
  const locStr = [prop?.location_admin?.village, prop?.location_admin?.taluka, prop?.location_admin?.district]
    .filter(Boolean).join(", ");
  if (locStr) {
    doc.fontSize(12).font("Helvetica").fillColor("#333").text(locStr);
  }
  doc.moveDown();

  // Area & use
  const acres = prop?.parcel?.area?.acres ? prop.parcel.area.acres.toFixed(2) : null;
  kv(doc, "Area (acres)", acres);
  kv(doc, "Area (hectares)", prop?.parcel?.area?.hectares);
  kv(doc, "Land use", prop?.use_and_crop?.land_use);
  doc.moveDown();

  // Coordinates
  if (Array.isArray(prop?.geo?.coordinates)) {
    kv(doc, "Coordinates [lng, lat]", `[${prop.geo.coordinates[0]}, ${prop.geo.coordinates[1]}]`);
    kv(doc, "Geo source", prop?.geo?.geo_source);
    doc.moveDown();
  }

  // Nearby summary
  doc.font("Helvetica-Bold").fontSize(14).text("Nearby & Benefits");
  doc.moveDown(0.4);
  const c = prop?.computed || {};

  function row(label, item) {
    if (!item?.name) return;
    const km = item?.distance_m != null ? (item.distance_m / 1000).toFixed(1) + " km" : "";
    doc.font("Helvetica-Bold").text(`${label}: `, { continued: true });
    doc.font("Helvetica").text(`${item.name}${km ? ` (${km})` : ""}`);
  }

  const bullets = [];
  if (c.roadTouch) bullets.push("Road touch property");
  if (c.nearestHighway?.name) bullets.push(`Nearest Highway: ${c.nearestHighway.name}`);
  if (c.nearestMajorRoad?.name) bullets.push(`Nearest Major Road: ${c.nearestMajorRoad.name}`);
  if (bullets.length) {
    doc.font("Helvetica").text("• " + bullets.join("\n• "));
    doc.moveDown(0.5);
  }

  row("Village", c.nearestVillage);
  row("Taluka HQ", c.nearestTalukaHQ);
  row("District HQ", c.nearestDistrictHQ);
  row("Market", c.market);
  if (Array.isArray(c.rivers) && c.rivers[0]) row("River", c.rivers[0]);
  if (c.transport?.rail) row("Rail", c.transport.rail);
  if (c.transport?.bus) row("Bus Stand", c.transport.bus);

  // Schools & Hospitals lists
  function listGroup(label, arr) {
    if (!Array.isArray(arr) || !arr.length) return;
    doc.moveDown(0.4);
    doc.font("Helvetica-Bold").text(label);
    arr.slice(0, 5).forEach((x) => {
      const km = x?.distance_m != null ? (x.distance_m / 1000).toFixed(1) + " km" : "";
      doc.font("Helvetica").text(`• ${x.name}${km ? ` (${km})` : ""}`);
    });
  }
  listGroup("Schools", c.schools);
  listGroup("Hospitals", c.hospitals);
  listGroup("Industries", c.industries);

  // Footer
  doc.moveDown();
  doc.fontSize(10).fillColor("#777").text("Generated by Chandrapur Real Estate", { align: "right" });

  doc.end();
}
